services:
  web-portal:
    container_name: web-portal-dev
    image: jeffavery/web-portal-dev:local
    build:
      context: .
    restart: unless-stopped

    volumes:
      - ./data:/app/data

    ports:
      - "8788:8000"

    environment:
      SECRET_KEY: "${SECRET_KEY}"
      LOG_LEVEL: "INFO"
      SHOW_VERSION_NUMBER: "true"
      ALLOW_BACKGROUND_IMAGE_UPLOAD: "true"
      ALLOW_ICON_UPLOADS: "true"
      OPEN_TO_NEW_TAB: "true"
